CREATE SCHEMA IF NOT EXISTS SCHEMA_PADRAO;

CREATE SEQUENCE IF NOT EXISTS SCHEMA_PADRAO.SEQUENCE_PADRAO INCREMENT 1 START 1;

CREATE TABLE IF NOT EXISTS SCHEMA_PADRAO.TB_TAREFAS (
	ID INT NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DATA_ENTREGA TIMESTAMP NOT NULL,
	RESPONSAVEL VARCHAR(100) NOT NULL
);

ALTER TABLE SCHEMA_PADRAO.TB_TAREFAS
ADD CONSTRAINT PK_TAREFAS PRIMARY KEY (ID);